import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import test from "node:test";

const repoRoot = path.resolve(import.meta.dirname, "..", "..");
const browserFirstRoot = path.join(repoRoot, "browser-first");
const extensionRoot = path.join(browserFirstRoot, "resonantos-side-panel-extension");

const readJson = async (filePath) => JSON.parse(await readFile(filePath, "utf8"));
const readText = (filePath) => readFile(filePath, "utf8");

test("ADR-037 makes browser-first Chromium the product direction", async () => {
  const adr = await readText(path.join(repoRoot, "docs", "architecture", "ADR-037-browser-first-chromium-resonantos.md"));
  const adr035 = await readText(path.join(repoRoot, "docs", "architecture", "ADR-035-electron-host-rust-core-runtime.md"));
  const adr036 = await readText(path.join(repoRoot, "docs", "architecture", "ADR-036-wallet-capable-browser-host.md"));

  assert.match(adr, /browser-first application/i);
  assert.match(adr, /Chromium-family browser/i);
  assert.match(adr, /not a ResonantOS dashboard that opens or controls another browser/i);
  assert.match(adr, /Phantom Wallet must run in the same browser profile/i);
  assert.match(adr, /Do not present external Chrome\/Brave CDP control as the product Browser/i);
  assert.match(adr035, /Superseded by ADR-037/);
  assert.match(adr036, /Superseded by ADR-037/);
});

test("ResonantOS browser layer is packaged as a Chromium side-panel extension", async () => {
  const manifest = await readJson(path.join(extensionRoot, "manifest.json"));

  assert.equal(manifest.manifest_version, 3);
  assert.equal(manifest.name, "ResonantOS Browser Layer");
  assert.equal(manifest.version, "0.1.1");
  assert.equal(manifest.key.length > 100, true);
  assert.ok(manifest.permissions.includes("sidePanel"));
  assert.ok(manifest.permissions.includes("activeTab"));
  assert.ok(manifest.permissions.includes("clipboardRead"));
  assert.ok(manifest.permissions.includes("clipboardWrite"));
  assert.ok(manifest.permissions.includes("history"));
  assert.ok(manifest.permissions.includes("scripting"));
  assert.ok(manifest.permissions.includes("tabs"));
  assert.ok(manifest.permissions.includes("webNavigation"));
  assert.equal(manifest.content_scripts[0].all_frames, true);
  assert.equal(manifest.side_panel.default_path, "src/side-panel.html");
  assert.equal(manifest.chrome_url_overrides.newtab, "src/main-workspace.html");
  assert.equal(manifest.background.type, "module");
  assert.equal(manifest.background.service_worker, "src/background.js");
  assert.equal(manifest.commands["open-augmentor-side-panel"].suggested_key.mac, "Alt+Shift+A");
});

test("browser-first main workspace owns new-tab AI chat and hands browser tasks to the sidebar", async () => {
  const manifest = await readJson(path.join(extensionRoot, "manifest.json"));
  const workspace = await readText(path.join(extensionRoot, "src", "main-workspace.html"));
  const workspaceScript = await readText(path.join(extensionRoot, "src", "main-workspace.js"));
  const workspaceStyles = await readText(path.join(extensionRoot, "src", "main-workspace.css"));
  const launcher = await readText(path.join(browserFirstRoot, "host", "run-browser-first.mjs"));
  const background = await readText(path.join(extensionRoot, "src", "background.js"));
  const sidePanel = await readText(path.join(extensionRoot, "src", "side-panel.js"));

  assert.equal(manifest.chrome_url_overrides.newtab, "src/main-workspace.html");
  assert.match(workspace, /ResonantOS main workspace/);
  assert.match(workspace, /chat-history/);
  assert.match(workspace, /Living Archive/);
  assert.match(workspace, /Hermes/);
  assert.match(workspace, /OpenCode/);
  assert.match(workspace, /mode-select/);
  assert.match(workspace, /model-select/);
  assert.match(workspace, /thinking-depth/);
  assert.match(workspace, /Open Sidebar/);
  assert.match(workspace, /main-workspace\.js/);
  assert.match(workspaceScript, /createChatSessionStore/);
  assert.match(workspaceScript, /\/augmentor\/chat/);
  assert.match(workspaceScript, /response\?\.reply/);
  assert.match(workspaceScript, /parseAutonomousBrowserActionIntent/);
  assert.match(workspaceScript, /parseNaturalBrowserIntent/);
  assert.match(workspaceScript, /augmentorPendingSidebarPrompt/);
  assert.match(workspaceScript, /open_side_panel/);
  assert.match(workspaceScript, /chrome\.tabs\.update/);
  assert.match(workspaceScript, /commandForm\.requestSubmit\(\)/);
  assert.match(workspaceScript, /renderHermesWorkspace/);
  assert.match(workspaceScript, /document\.body\.dataset\.workspace/);
  assert.match(workspaceScript, /\/addons\/status/);
  assert.match(workspaceScript, /\/hermes\/dashboard\/status/);
  assert.match(workspaceScript, /\/hermes\/dashboard\/start/);
  assert.match(workspaceScript, /\/hermes\/dashboard\/stop/);
  assert.match(workspaceScript, /\/addons\/delegate/);
  assert.match(workspaceScript, /target: "hermes"/);
  assert.match(workspaceScript, /parseHermesSlashCommand/);
  assert.match(workspaceScript, /iframe\.src = dashboard\.url/);
  assert.match(workspaceStyles, /workspace-shell/);
  assert.match(workspaceStyles, /answer-workspace/);
  assert.match(workspaceStyles, /module-workspace/);
  assert.match(workspaceStyles, /dashboard-frame-card/);
  assert.match(launcher, /defaultMainWorkspaceUrl/);
  assert.match(launcher, /\/hermes\/dashboard\/status/);
  assert.match(launcher, /\/hermes\/dashboard\/start/);
  assert.match(launcher, /\/hermes\/dashboard\/stop/);
  assert.match(launcher, /Hermes dashboard can only bind to localhost/);
  assert.match(launcher, /main-workspace\.html/);
  assert.match(background, /open_side_panel/);
  assert.match(sidePanel, /consumePendingSidebarPrompt/);
  assert.match(sidePanel, /chrome\.storage\?\.onChanged/);
});

test("browser layer has a human approval boundary for wallet and credential actions", async () => {
  const background = await readText(path.join(extensionRoot, "src", "background.js"));
  const panel = await readText(path.join(extensionRoot, "src", "side-panel.html"));
  const script = await readText(path.join(extensionRoot, "src", "side-panel.js"));

  assert.match(background, /wallet_connect/);
  assert.match(background, /wallet_sign/);
  assert.match(background, /credential_autofill/);
  assert.match(background, /deniedToAutomation/);
  assert.match(panel, /Message Augmentor/);
  assert.match(script, /Wallet actions are human-approval gated/);
});

test("browser layer exposes Augmentor chat as the side-panel surface without stealing the browser tab", async () => {
  const panel = await readText(path.join(extensionRoot, "src", "side-panel.html"));
  const script = await readText(path.join(extensionRoot, "src", "side-panel.js"));
  const appCommandHandlers = await readText(path.join(extensionRoot, "src", "lib", "app-command-handlers.js"));
  const bridgeClient = await readText(path.join(extensionRoot, "src", "lib", "bridge-client.js"));
  const commandParser = await readText(path.join(extensionRoot, "src", "lib", "browser-command-parser.js"));
  const browserJobStore = await readText(path.join(extensionRoot, "src", "lib", "browser-job-store.js"));
  const chatTurnController = await readText(path.join(extensionRoot, "src", "lib", "chat-turn-controller.js"));
  const composerController = await readText(path.join(extensionRoot, "src", "lib", "composer-controller.js"));
  const controlPageObserver = await readText(path.join(extensionRoot, "src", "lib", "control-page-observer.js"));
  const controlPlanningService = await readText(path.join(extensionRoot, "src", "lib", "control-planning-service.js"));
  const controlReportingService = await readText(path.join(extensionRoot, "src", "lib", "control-reporting-service.js"));
  const controlRunState = await readText(path.join(extensionRoot, "src", "lib", "control-run-state.js"));
  const controlStepExecutor = await readText(path.join(extensionRoot, "src", "lib", "control-step-executor.js"));
  const approvalPolicy = await readText(path.join(extensionRoot, "src", "lib", "approval-policy.js"));
  const agentControlPlanner = await readText(path.join(extensionRoot, "src", "lib", "agent-control-planner.js"));
  const agentControlRunner = await readText(path.join(extensionRoot, "src", "lib", "agent-control-runner.js"));
  const pageActions = await readText(path.join(extensionRoot, "src", "lib", "browser-page-actions.js"));
  const chatSessionStore = await readText(path.join(extensionRoot, "src", "lib", "chat-session-store.js"));
  const messageActionController = await readText(path.join(extensionRoot, "src", "lib", "message-action-controller.js"));
  const sidePanelRenderers = await readText(path.join(extensionRoot, "src", "lib", "side-panel-renderers.js"));
  const monitorRenderers = await readText(path.join(extensionRoot, "src", "lib", "monitor-renderers.js"));
  const commandRouter = await readText(path.join(extensionRoot, "src", "lib", "side-panel-command-router.js"));
  const sitePermissionStore = await readText(path.join(extensionRoot, "src", "lib", "site-permission-store.js"));
  const tabContextController = await readText(path.join(extensionRoot, "src", "lib", "tab-context-controller.js"));
  const background = await readText(path.join(extensionRoot, "src", "background.js"));

  assert.match(panel, /Message Augmentor/);
  assert.match(panel, /new-chat/);
  assert.match(panel, /chat-history/);
  assert.match(panel, /bridge-config\.generated\.js/);
  assert.match(panel, /control-monitor/);
  assert.match(panel, /context-dock"[^>]+hidden/);
  assert.match(panel, /context-toggle/);
  assert.match(panel, /approval-card/);
  assert.match(panel, /approval-trust-site/);
  assert.match(panel, /site-permission-panel/);
  assert.match(panel, /job-monitor/);
  assert.match(panel, /trusted-for-safe-actions/);
  assert.doesNotMatch(panel, /I.m here in the browser side bar/);
  assert.doesNotMatch(panel, /Current page/);
  assert.match(panel, /Connected model/);
  assert.match(panel, /Thinking depth/);
  assert.match(panel, /Intake/);
  assert.match(background, /openPanelOnActionClick/);
  assert.match(background, /openResonantSidePanel/);
  assert.match(background, /open-augmentor-side-panel/);
  assert.doesNotMatch(background, /chrome\.tabs\.create/);
  assert.doesNotMatch(background, /chrome\.tabs\.onUpdated/);
  assert.match(script, /isReadableBrowserTab/);
  assert.match(pageActions, /currentWindow: true/);
  assert.match(pageActions, /summarizeSnapshot/);
  assert.match(script, /saveIntake/);
  assert.match(script, /createChatSessionStore/);
  assert.match(script, /createChatTurnController/);
  assert.match(chatTurnController, /\/augmentor\/chat/);
  assert.match(chatTurnController, /pageContextForSnapshot/);
  assert.match(chatTurnController, /runtimeContextForAttachments/);
  assert.match(chatTurnController, /providerMessagesFromHistory/);
  assert.match(script, /createComposerController/);
  assert.match(composerController, /handleClipboardShortcut/);
  assert.match(composerController, /resetUndoStack/);
  assert.match(composerController, /requestSubmit/);
  assert.match(script, /createMessageActionController/);
  assert.match(messageActionController, /copyMessage/);
  assert.match(messageActionController, /forkFromMessage/);
  assert.match(messageActionController, /saveMessageToArchive/);
  assert.match(messageActionController, /regenerateFromMessage/);
  assert.match(messageActionController, /attachFiles/);
  assert.match(chatSessionStore, /forkFromMessage/);
  assert.match(chatSessionStore, /createSession/);
  assert.match(chatSessionStore, /switchSession/);
  assert.match(chatSessionStore, /getSessions/);
  assert.match(chatSessionStore, /trimToPreviousUserMessage/);
  assert.match(chatSessionStore, /addAttachments/);
  assert.match(chatSessionStore, /hydrate/);
  assert.match(script, /createSidePanelRenderers/);
  assert.match(script, /createAppCommandHandlers/);
  assert.match(appCommandHandlers, /runGoalCommand/);
  assert.match(appCommandHandlers, /runSitePermissionCommand/);
  assert.match(appCommandHandlers, /runJobsCommand/);
  assert.match(appCommandHandlers, /pauseBrowserJob/);
  assert.match(script, /createSidePanelCommandRouter/);
  assert.match(commandRouter, /respondToCommand/);
  assert.match(commandRouter, /name === "hermes"/);
  assert.match(commandRouter, /parseControlIntent/);
  assert.match(commandRouter, /handleWalletBoundary/);
  assert.match(sidePanelRenderers, /renderMessages/);
  assert.match(sidePanelRenderers, /What should Augmentor work on/);
  assert.match(sidePanelRenderers, /renderAttachments/);
  assert.match(sidePanelRenderers, /flashCopied/);
  assert.match(script, /createSitePermissionStore/);
  assert.match(sitePermissionStore, /siteKeyForUrl/);
  assert.match(sitePermissionStore, /permissionForUrl/);
  assert.match(sitePermissionStore, /setSitePermission/);
  assert.match(sitePermissionStore, /ask-before-action/);
  assert.match(script, /createMonitorRenderers/);
  assert.match(monitorRenderers, /sitePermissionDescription/);
  assert.match(monitorRenderers, /renderSitePermissionPanel/);
  assert.match(monitorRenderers, /renderJobMonitor/);
  assert.match(monitorRenderers, /renderControlMonitor/);
  assert.match(script, /createTabContextController/);
  assert.match(tabContextController, /resolveTabMention/);
  assert.match(tabContextController, /bindMentionedTab/);
  assert.match(tabContextController, /consumeInlineDraft/);
  assert.match(tabContextController, /bindBrowserListeners/);
  assert.match(tabContextController, /hydrateInitialContext/);
  assert.match(script, /createBridgeClient/);
  assert.match(bridgeClient, /bridgeUrl = config\.bridgeUrl \?\? "http:\/\/127\.0\.0\.1:47773"/);
  assert.match(bridgeClient, /__RESONANTOS_BRIDGE_CONFIG__/);
  assert.match(bridgeClient, /X-ResonantOS-Bridge-Token/);
  assert.match(script, /browserJobStore\.getMonitorCollapsed/);
  assert.match(chatTurnController, /\/augmentor\/chat/);
  assert.match(controlReportingService, /\/archive\/intake/);
  assert.match(appCommandHandlers, /\/memory\/search/);
  assert.match(appCommandHandlers, /\/addons\/delegate/);
  assert.match(appCommandHandlers, /\/goals/);
  assert.match(commandParser, /parseNaturalBrowserIntent/);
  assert.match(script, /createBrowserJobStore/);
  assert.match(browserJobStore, /normalizeBrowserJob/);
  assert.match(browserJobStore, /createBrowserJobStore/);
  assert.match(browserJobStore, /toggleMonitorCollapsed/);
  assert.match(browserJobStore, /findJob/);
  assert.match(commandParser, /parseNaturalSearchIntent/);
  assert.match(commandParser, /parseTypeIntent/);
  assert.match(commandParser, /parseClickIntent/);
  assert.match(commandParser, /parseReadPageIntent/);
  assert.match(commandParser, /parseStructuredPageEditIntent/);
  assert.match(commandParser, /parseScrollIntent/);
  assert.match(commandParser, /parseFormsIntent/);
  assert.match(commandParser, /parseControlIntent/);
  assert.match(commandParser, /parseAutonomousBrowserActionIntent/);
  assert.match(commandParser, /parseAmazonShoppingTask/);
  assert.match(appCommandHandlers, /runHistorySearchCommand/);
  assert.match(appCommandHandlers, /runSitePermissionCommand/);
  assert.match(appCommandHandlers, /runCapabilitiesCommand/);
  assert.match(script, /approvalBoundaryForStep/);
  assert.match(script, /controlStepLabel/);
  assert.match(agentControlPlanner, /planControlSteps/);
  assert.match(agentControlPlanner, /deterministicNextAction/);
  assert.match(agentControlPlanner, /dedupeControlSteps/);
  assert.match(agentControlPlanner, /controlStepLabel/);
  assert.match(script, /trustCurrentSiteForSafeActions/);
  assert.match(appCommandHandlers, /runJobsCommand/);
  assert.match(appCommandHandlers, /pauseBrowserJob/);
  assert.match(appCommandHandlers, /resumeBrowserJob/);
  assert.match(appCommandHandlers, /cancelBrowserJob/);
  assert.match(script, /augmentorBrowserJobs/);
  assert.match(script, /renderSitePermissionPanel/);
  assert.match(script, /sitePermissionMode\.addEventListener/);
  assert.match(tabContextController, /resolveTabMention/);
  assert.match(tabContextController, /augmentorInlineDraft/);
  assert.match(pageActions, /searchBrowser/);
  assert.match(pageActions, /typeIntoActivePage/);
  assert.match(pageActions, /clickActivePageText/);
  assert.match(pageActions, /scrollActivePage/);
  assert.match(pageActions, /detectActivePageForms/);
  assert.match(script, /controlledTabId/);
  assert.match(controlStepExecutor, /switch_tab/);
  assert.match(agentControlPlanner, /List open tabs/);
  assert.match(agentControlPlanner, /planControlSteps/);
  assert.match(script, /createControlPlanningService/);
  assert.match(controlPlanningService, /requestControlPlan/);
  assert.match(controlPlanningService, /requestNextControlAction/);
  assert.match(agentControlRunner, /continueControlLoop/);
  assert.match(agentControlRunner, /observe-act-verify-loop/);
  assert.match(script, /createControlPageObserver/);
  assert.match(controlPageObserver, /observeControlPage/);
  assert.match(controlPageObserver, /listReadableTabSnapshots/);
  assert.match(controlPageObserver, /Browser job is paused/);
  assert.match(controlPageObserver, /Browser job was cancelled/);
  assert.match(approvalPolicy, /sanitizePlannerStep/);
  assert.match(approvalPolicy, /sanitizeNextActionDecision/);
  assert.match(approvalPolicy, /sanitizePlannerPlan/);
  assert.match(approvalPolicy, /approvalBoundaryForStep/);
  assert.match(controlPlanningService, /planAgentControlSteps/);
  assert.match(controlPlanningService, /__resonantosControlPlannerOverride/);
  assert.match(controlPlanningService, /__resonantosNextActionOverride/);
  assert.match(script, /createControlStepExecutor/);
  assert.match(controlStepExecutor, /executeControlStep/);
  assert.match(controlStepExecutor, /listReadableTabs/);
  assert.match(controlStepExecutor, /Unknown control step/);
  assert.match(agentControlRunner, /runControlCommand/);
  assert.match(script, /renderControlMonitor/);
  assert.match(agentControlRunner, /approvePendingControlStep/);
  assert.match(agentControlRunner, /denyPendingControlStep/);
  assert.match(script, /createControlReportingService/);
  assert.match(controlReportingService, /buildControlReport/);
  assert.match(controlReportingService, /saveControlReportToArchive/);
  assert.match(controlReportingService, /delegateControlIssue/);
  assert.match(controlReportingService, /Browser Agent Control Report/);
  assert.match(script, /createControlRunState/);
  assert.match(controlRunState, /startControlRun/);
  assert.match(controlRunState, /appendControlStep/);
  assert.match(controlRunState, /updateControlStep/);
  assert.match(controlRunState, /finishControlRun/);
  assert.match(controlRunState, /setPageControlOverlay/);
  assert.match(agentControlRunner, /Agent Control Mode started/);
  assert.match(script, /explainStructuredPageEditBoundary/);
  assert.match(pageActions, /bing\.com\/news\/search/);
  assert.match(pageActions, /\/web\/news/);
  assert.match(script, /turnBusy/);
  assert.match(script, /setActivity/);
  assert.match(pageActions, /openBrowserUrl/);
  assert.match(pageActions, /chrome\.tabs\.update/);
  assert.match(pageActions, /chrome\.tabs\.create/);
  assert.match(messageActionController, /copyMessage/);
  assert.match(sidePanelRenderers, /message-action/);
  assert.match(composerController, /commandInput\.addEventListener\("keydown"/);
  assert.match(composerController, /commandForm\.requestSubmit\(\)/);
  assert.match(composerController, /event\.metaKey/);
  assert.match(composerController, /undoInput/);
  assert.match(composerController, /shortcutKey === "z"/);
  assert.match(messageActionController, /forkFromMessage/);
  assert.match(messageActionController, /editMessage/);
  assert.match(messageActionController, /saveMessageToArchive/);
  assert.match(messageActionController, /regenerateFromMessage/);
  assert.match(messageActionController, /deleteMessage/);
  assert.doesNotMatch(script, /Full LLM replies will come from/);
});

test("browser layer can read active tab context without raw privileged access", async () => {
  const content = await readText(path.join(extensionRoot, "src", "content.js"));
  const panel = await readText(path.join(extensionRoot, "src", "side-panel.js"));
  const pageActions = await readText(path.join(extensionRoot, "src", "lib", "browser-page-actions.js"));

  assert.match(content, /read_page/);
  assert.match(content, /click_text/);
  assert.match(content, /type_text/);
  assert.match(content, /resonantos-control-overlay/);
  assert.match(content, /control_overlay/);
  assert.match(content, /controlPhaseDetails/);
  assert.match(content, /ros-control-status-text/);
  assert.match(content, /ros-control-stop-button/);
  assert.match(content, /cancel_control_run/);
  assert.match(content, /Reading page\.\.\./);
  assert.match(content, /Typing\.\.\./);
  assert.match(content, /Taking screenshot\.\.\.|Clicking\.\.\.|Working\.\.\./);
  assert.match(content, /setControlSessionOverlay/);
  assert.match(content, /isTopWindow/);
  assert.match(content, /phase: message\.phase/);
  assert.match(content, /data-session="active"/);
  assert.match(content, /pulseControlOverlay/);
  assert.match(content, /resonantos-control-target/);
  assert.match(content, /resonantos-control-bubble/);
  assert.match(content, /showControlActionBubble/);
  assert.match(content, /userApproved/);
  assert.match(content, /isHardRestrictedElement/);
  assert.match(content, /scroll_page/);
  assert.match(content, /detect_forms/);
  assert.match(content, /clickVisibleText/);
  assert.match(content, /typeIntoPage/);
  assert.match(content, /scrollPage/);
  assert.match(content, /describeForms/);
  assert.match(content, /controls: candidateClickElements/);
  assert.match(content, /data-resonantos-control-ref/);
  assert.match(content, /resonantos-inline-assistant/);
  assert.match(content, /ros-inline-prompt/);
  assert.match(content, /data-action="custom"/);
  assert.match(content, /currentSitePermission/);
  assert.match(content, /augmentorInlineDraft/);
  assert.match(content, /ensureControlRef/);
  assert.match(content, /clickControlRef/);
  assert.match(content, /fields: Array\.from/);
  assert.match(content, /viewport/);
  assert.match(content, /approvalRequired/);
  assert.match(content, /document\.body\?\.innerText/);
  assert.match(content, /phantomSolana/);
  assert.match(pageActions, /chrome\.tabs\.sendMessage/);
  assert.match(pageActions, /phase/);
  assert.match(pageActions, /chrome\.scripting/);
  assert.match(pageActions, /executeScript/);
  assert.match(pageActions, /chrome\.webNavigation/);
  assert.match(pageActions, /mergeFrameSnapshots/);
  assert.doesNotMatch(content, /eval\(/);
  assert.doesNotMatch(panel, /eval\(/);
});

test("browser-first host is a runnable app path, not documentation-only scaffolding", async () => {
  const packageJson = await readJson(path.join(repoRoot, "package.json"));
  const launcher = await readText(path.join(browserFirstRoot, "host", "run-browser-first.mjs"));
  const bridgeServer = await readText(path.join(browserFirstRoot, "host", "bridge-server.mjs"));
  const installer = await readText(path.join(repoRoot, "scripts", "install-browser-first-app.mjs"));
  const nativeHost = await readText(
    path.join(repoRoot, "addons", "resonant-browser-native", "native_host", "src", "resonant_browser_native_host.cc"),
  );

  assert.match(packageJson.scripts["browser-first:dev"], /run-browser-first\.mjs/);
  assert.match(packageJson.scripts["browser-first:install"], /install-browser-first-app\.mjs/);
  assert.match(installer, /ResonantOS Browser\.app/);
  assert.match(launcher, /--resonantos-browser-first/);
  assert.match(launcher, /resonantos-side-panel-extension/);
  assert.match(launcher, /bfnaelmomeimhlpmgjnjophhpkkoljpa/);
  assert.match(launcher, /pinned_extensions/);
  assert.match(launcher, /cdpdmmalhmokbfcfgogoepnjplaakgnl/);
  assert.match(launcher, /auto-open-side-panel/);
  assert.match(launcher, /remote-debugging-port/);
  assert.match(launcher, /resonantos-remote-debugging-port/);
  assert.match(launcher, /createBridgeToken/);
  assert.match(launcher, /writeBridgeConfig/);
  assert.match(launcher, /startBridgeServer/);
  assert.match(bridgeServer, /bridge-config\.generated\.js/);
  assert.match(bridgeServer, /X-ResonantOS-Bridge-Token/);
  assert.match(bridgeServer, /Unauthorized browser-first bridge request/);
  assert.doesNotMatch(bridgeServer, /Access-Control-Allow-Origin": "\*"/);
  assert.match(launcher, /provider-secrets\.json/);
  assert.match(launcher, /\/augmentor\/chat/);
  assert.match(launcher, /\/augmentor\/inline/);
  assert.match(launcher, /executeInlineAssistant/);
  assert.match(launcher, /customInstruction/);
  assert.match(launcher, /\/augmentor\/control-plan/);
  assert.match(launcher, /\/augmentor\/next-action/);
  assert.match(launcher, /executeNextAction/);
  assert.match(launcher, /sanitizeNextActionDecision/);
  assert.match(launcher, /switch_tab/);
  assert.match(launcher, /sanitizeControlStep/);
  assert.match(launcher, /sanitizeControlPlan/);
  assert.match(launcher, /executeControlPlan/);
  assert.match(launcher, /strict JSON only/);
  assert.match(launcher, /observed refs/);
  assert.match(launcher, /The web page remains in the main browser viewport/);
  assert.match(launcher, /host-mediated browser tools/);
  assert.match(launcher, /click visible page text/);
  assert.match(launcher, /\/memory\/status/);
  assert.match(launcher, /\/memory\/search/);
  assert.match(launcher, /\/archive\/intake/);
  assert.match(launcher, /\/addons\/delegate/);
  assert.match(launcher, /\/web\/news/);
  assert.match(launcher, /news\.google\.com\/rss/);
  assert.match(launcher, /keystroke \\"a\\" using \{option down, shift down\}/);
  assert.match(nativeHost, /resonantos-browser-first/);
  assert.match(nativeHost, /resonantos-remote-debugging-port/);
  assert.match(nativeHost, /CefKeyboardHandler/);
  assert.match(nativeHost, /EVENTFLAG_COMMAND_DOWN/);
  assert.match(nativeHost, /windows_key_code == 'Q'/);
  assert.match(nativeHost, /browser\.first\.started/);
  assert.match(nativeHost, /resonantos-user-data-dir/);
});

test("browser-first bridge rejects unauthenticated localhost requests", () => {
  const result = spawnSync(
    "node",
    [
      path.join(browserFirstRoot, "host", "run-browser-first.mjs"),
      "--bridge-auth-self-test=true",
      "--bridge-token=test-token",
      "--bridge-port=0",
    ],
    {
      cwd: repoRoot,
      encoding: "utf8",
      timeout: 10_000,
    },
  );

  assert.equal(result.status, 0, result.stderr || result.stdout);
  const payload = JSON.parse(result.stdout);
  assert.equal(payload.ok, true);
  assert.equal(payload.unauthorizedStatus, 401);
  assert.equal(payload.wrongTokenStatus, 401);
  assert.equal(payload.authorizedStatus, 200);
});
